Repository aquaproj/aqua-installer, pull requests merged in 2022-01, with the labels that each got.

#78 feat: validate aqua_version
  README.md
  action.yml
Labels: enhancement, breaking change

#81 feat: support aqua >= v0.10.0
  .github/workflows/test-actions.yml
  action.yml
Labels: breaking change

#86 Rename a file extension to fix broken links
  action.yaml
Labels: bug

#88 feat: change the default install_path
  .github/workflows/test.yml
  README.md
  action.sh
  action.yaml
  aqua-installer
Labels: enhancement, breaking change
