Repository aquaproj/aqua-installer, pull requests merged in 2022-12, with the labels that each got.

#286 feat: add support for PowerShell
  .github/workflows/test-actions-windows-bash.yaml
  action.yaml
Labels: enhancement

#277 feat: verify aqua with slsa-verifier
  .github/workflows/integration-test.yaml
  .github/workflows/test-actions-windows-bash.yaml
  .github/workflows/test-actions.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test.yaml
  README.md
  action.sh
  action.yaml
  aqua-installer
  go.mod
  go.sum
  main.go
  pkg/api/api.go
  pkg/api/root_dir.go
  pkg/api/root_dir_windows.go
  pkg/api/unarchive.go
Labels: enhancement, breaking change, security, cosign

#298 ci: limit GitHub Actions Workflow permissions
  .github/workflows/actionlint.yaml
  .github/workflows/renovate-config-validator.yaml
  .github/workflows/test-actions-windows-bash.yaml
  .github/workflows/test-actions.yaml
  .github/workflows/test.yaml
Labels: security

#297 docs: update README
  README.md
Labels: documentation

#300 ci: test in macOS
  .github/workflows/test-actions-windows-bash.yaml
  .github/workflows/test-macos.yaml
  aqua-installer
Labels: bug

#303 chore: update bootstrap aqua to 1.26.2
  aqua-installer
Labels: bug

#306 docs: fix how to install aqua with Go
  README.md
Labels: documentation

#309 docs: verify aqua-installer's checksum
  README.md
Labels: documentation
